version: '3'

services:
  app:
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - 3000:3000
    networks:
      - my_network
    environment:
      - MONGO_URL=mongodb://database:27017/
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/live || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s

  database:
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - my_network
    volumes:
      - mongo_vol:/data/db
    
networks:
  my_network:
    driver: bridge

volumes:
 mongo_vol: